export const USER = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  UNSET_CURRENT_USER: 'UNSET_CURRENT_USER',
  TOGGLE_AUTH_IN_PROGRESS: 'TOGGLE_AUTH_IN_PROGRESS'
};

export const ERROR = {
	SET_ERROR: 'SET_ERROR',
	UNSET_ERROR: 'UNSET_ERROR'
};

export const PRODUCT = {
  SET_PACKAGE_LIST: 'SET_PACKAGE_LIST',
  UNSET_PACKAGE_LIST: 'UNSET_PACKAGE_LIST',
  TOGGLE_FETCHING_PACKAGE_LIST: 'TOGGLE_FETCHING_PACKAGE_LIST',
  SET_PACKAGE_SLOTS: 'SET_PACKAGE_SLOTS',
  UNSET_PACKAGE_SLOTS: 'UNSET_PACKAGE_SLOTS',
  TOGGLE_FETCHING_PACKAGE_SLOTS: 'TOGGLE_FETCHING_PACKAGE_SLOTS'
};